import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class Register
 */
@WebServlet("/Register")
public class Register extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public Register() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String id=request.getParameter("school");
		RegisterDao rdao=new RegisterDao();
		String result=rdao.insert_school_id(id);
		response.getWriter().println(result);
	}
}

//import java.io.IOException;
//import javax.servlet.ServletException;
//import javax.servlet.annotation.WebServlet;
//import javax.servlet.http.HttpServlet;
//import javax.servlet.http.HttpServletRequest;
//import javax.servlet.http.HttpServletResponse;
//import java.io.PrintWriter;
//
//@WebServlet("/Register")
//public class Register extends HttpServlet {
//    protected void doGet(HttpServletRequest request, HttpServletResponse response)
//            throws ServletException, IOException {
//        // Set the content type to HTML
//        response.setContentType("text/html");
//
//        // Get the PrintWriter object to write HTML content to the response
//        PrintWriter out = response.getWriter();
//
//        // Write the HTML content
//        out.println("<html>");
//        out.println("<head><title>Simple Servlet Example</title></head>");
//        out.println("<body>");
//        out.println("<h1>Hello, This is a Simple Servlet!</h1>");
//        out.println("<p>This is a static HTML page generated by a servlet.</p>");
//        out.println("</body>");
//        out.println("</html>");
//    }
//}
